<?php
$accdatabase="D:\LeadDB_ThisSMALL.mdb";

try {
    # OPEN BOTH DATABASE CONNECTIONS
    $db = new PDO("odbc:Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBq=$accdatabase;Uid=;Pwd=;");
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    $Alit_CA_Windows_Doors = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput_Alit_ALL JOB].Address, [002_DateInput_Alit_ALL JOB].City, [002_DateInput_Alit_ALL JOB].State, [002_DateInput_Alit_ALL JOB].Zip, [002_DateInput_Alit_ALL JOB].Phone, [002_DateInput_Alit_ALL JOB].[Job Group], '---------' AS Stop, LeadsDb.SystemCreateDate, [Shai Alit Cities Not].[Shai Alit Cities Not], [005f4_Palm CON LA PANT --PASS].Phone AS PhoneNotCalled, County.COUNTY AS County, Len(LeadsDb!conDayTimePhone) AS LengthPhone
FROM [Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN ([005f4_Palm CON LA PANT --PASS] RIGHT JOIN (LeadsDb INNER JOIN [002_DateInput_Alit_ALL JOB] ON LeadsDb.ID = [002_DateInput_Alit_ALL JOB].ID) ON [005f4_Palm CON LA PANT --PASS].Phone = [002_DateInput_Alit_ALL JOB].Phone) ON County.ZIPCODE = [002_DateInput_Alit_ALL JOB].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput_Alit_ALL JOB].City
WHERE ((([002_DateInput_Alit_ALL JOB].State)='CA') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Like '%Window%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND (([005f4_Palm CON LA PANT --PASS].Phone) Is Null) AND ((County.COUNTY) Like 'os Angeles' Or (County.COUNTY)='Ventura' Or (County.COUNTY)='Riverside' Or (County.COUNTY)='San Bernardino' Or (County.COUNTY)='Orange' Or (County.COUNTY)='Santa Barbara') AND ((Len([LeadsDb]![conDayTimePhone]))=10)) OR ((([002_DateInput_Alit_ALL JOB].State)='CA') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Like '%door%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like 'Build an Outdoor Kitchen') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND (([005f4_Palm CON LA PANT --PASS].Phone) Is Null) AND ((County.COUNTY) Like 'Los Angeles' Or (County.COUNTY)='Ventura' Or (County.COUNTY)='Riverside' Or (County.COUNTY)='San Bernardino' Or (County.COUNTY)='Orange' Or (County.COUNTY)='Santa Barbara') AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY LeadsDb.SystemCreateDate DESC";

    $Alit_ALL_Kitchen_Bathroom_Decks = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput_Alit_ALL JOB].Address, [002_DateInput_Alit_ALL JOB].City, [002_DateInput_Alit_ALL JOB].State, [002_DateInput_Alit_ALL JOB].Zip, [002_DateInput_Alit_ALL JOB].Phone, [002_DateInput_Alit_ALL JOB].[Job Group], County.COUNTY AS County1, '---------' AS Stop, LeadsDb.SystemCreateDate, [Shai Alit Cities Not].[Shai Alit Cities Not], Len(LeadsDb!conDayTimePhone) AS LengthPhone, [002_DateInput_Alit_ALL JOB].ID
FROM [Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN (LeadsDb INNER JOIN [002_DateInput_Alit_ALL JOB] ON LeadsDb.ID = [002_DateInput_Alit_ALL JOB].ID) ON County.ZIPCODE = [002_DateInput_Alit_ALL JOB].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput_Alit_ALL JOB].City
WHERE ((([002_DateInput_Alit_ALL JOB].State) Like 'CA' Or ([002_DateInput_Alit_ALL JOB].State)='TX' Or ([002_DateInput_Alit_ALL JOB].State)='WA' Or ([002_DateInput_Alit_ALL JOB].State)='OR') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Like '%Kitchen%' Or ([002_DateInput_Alit_ALL JOB].[Job Group]) Like '%Bath%' Or ([002_DateInput_Alit_ALL JOB].[Job Group]) Like '%deck%' Or ([002_DateInput_Alit_ALL JOB].[Job Group]) Like '%Renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY LeadsDb.SystemCreateDate DESC";

    $Alit_LA = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput_Alit_ALL JOB].Address, [002_DateInput_Alit_ALL JOB].City, [002_DateInput_Alit_ALL JOB].State, [002_DateInput_Alit_ALL JOB].Zip, [002_DateInput_Alit_ALL JOB].Phone, [002_DateInput_Alit_ALL JOB].[Job Group], '---------' AS Stop, LeadsDb.SystemCreateDate, [Shai Alit Cities Not].[Shai Alit Cities Not], [005f4_Palm CON LA PANT --PASS].Phone AS PhoneNotCalled, County.COUNTY AS County, Len(LeadsDb!conDayTimePhone) AS LengthPhone, [Sunset Roofing Leads Exclude].[Sunset Phone Roof Exclude]
FROM [Sunset Roofing Leads Exclude] RIGHT JOIN ([Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN ([005f4_Palm CON LA PANT --PASS] RIGHT JOIN (LeadsDb INNER JOIN [002_DateInput_Alit_ALL JOB] ON LeadsDb.ID = [002_DateInput_Alit_ALL JOB].ID) ON [005f4_Palm CON LA PANT --PASS].Phone = [002_DateInput_Alit_ALL JOB].Phone) ON County.ZIPCODE = [002_DateInput_Alit_ALL JOB].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput_Alit_ALL JOB].City) ON [Sunset Roofing Leads Exclude].[Sunset Phone Roof Exclude] = [002_DateInput_Alit_ALL JOB].Phone
WHERE ((([002_DateInput_Alit_ALL JOB].State)='CA') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Bath%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%deck%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Window%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%door%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND (([005f4_Palm CON LA PANT --PASS].Phone) Is Null) AND ((County.COUNTY) Like 'Los Angeles' Or (County.COUNTY)='Ventura' Or (County.COUNTY)='Riverside' Or (County.COUNTY)='San Bernardino' Or (County.COUNTY)='Orange' Or (County.COUNTY)='Santa Barbara') AND (([Sunset Roofing Leads Exclude].[Sunset Phone Roof Exclude]) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY LeadsDb.SystemCreateDate DESC";

    $Alit_SD = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput_Alit_ALL JOB].Address, [002_DateInput_Alit_ALL JOB].City, [002_DateInput_Alit_ALL JOB].State, [002_DateInput_Alit_ALL JOB].Zip, [002_DateInput_Alit_ALL JOB].Phone, [002_DateInput_Alit_ALL JOB].[Job Group], '---------' AS Stop, LeadsDb.SystemCreateDate, [Shai Alit Cities Not].[Shai Alit Cities Not], County.COUNTY AS County, Len(LeadsDb!conDayTimePhone) AS LengthPhone
FROM [Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN (LeadsDb INNER JOIN [002_DateInput_Alit_ALL JOB] ON LeadsDb.ID = [002_DateInput_Alit_ALL JOB].ID) ON County.ZIPCODE = [002_DateInput_Alit_ALL JOB].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput_Alit_ALL JOB].City
WHERE ((([002_DateInput_Alit_ALL JOB].State)='CA') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Bath%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%deck%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Window%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%door%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((County.COUNTY)='San Diego') AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY LeadsDb.SystemCreateDate DESC";

    $Alit_WA = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput_Alit_ALL JOB].Address, [002_DateInput_Alit_ALL JOB].City, [002_DateInput_Alit_ALL JOB].State, [002_DateInput_Alit_ALL JOB].Zip, [002_DateInput_Alit_ALL JOB].Phone, [002_DateInput_Alit_ALL JOB].[Job Group], '---------' AS Stop, LeadsDb.SystemCreateDate, [Shai Alit Cities Not].[Shai Alit Cities Not], County.COUNTY AS County, Len(LeadsDb!conDayTimePhone) AS LengthPhone
FROM [Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN (LeadsDb INNER JOIN [002_DateInput_Alit_ALL JOB] ON LeadsDb.ID = [002_DateInput_Alit_ALL JOB].ID) ON County.ZIPCODE = [002_DateInput_Alit_ALL JOB].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput_Alit_ALL JOB].City
WHERE ((([002_DateInput_Alit_ALL JOB].State)='WA') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Bath%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%deck%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Window%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%door%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((County.COUNTY) Not Like 'Clark') AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY LeadsDb.SystemCreateDate DESC";

    $Alit_BAY_South = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput].Address, [002_DateInput].City, [002_DateInput].State, [002_DateInput].Zip, [002_DateInput].Phone, [002_DateInput].[Job Group] AS [Job Group1], '---------' AS Stop, [002_DateInput].Date, [Shai Alit Cities Not].[Shai Alit Cities Not], County.COUNTY AS County, [002_DateInput].SystemCreateDate, [002_DateInput].[Submitted Date], [002_DateInput].company, [002_DateInput].ID, Len(LeadsDb!conDayTimePhone) AS LengthPhone
FROM [Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN (002_DateInput INNER JOIN LeadsDb ON [002_DateInput].ID = LeadsDb.ID) ON County.ZIPCODE = [002_DateInput].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput].City
WHERE ((([002_DateInput].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput].[Job Group]) Not Like '%Bath%' And ([002_DateInput].[Job Group]) Not Like '%deck%' And ([002_DateInput].[Job Group]) Not Like '%Window%' And ([002_DateInput].[Job Group]) Not Like '%door%' And ([002_DateInput].[Job Group]) Not Like '%renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((County.COUNTY) Like 'ALAMEDA' Or (County.COUNTY)='CONTRA COSTA' Or (County.COUNTY)='MARIN' Or (County.COUNTY)='MONTEREY' Or (County.COUNTY)='NAPA' Or (County.COUNTY)='SAN FRANCISCO' Or (County.COUNTY)='SAN JOAQUIN' Or (County.COUNTY)='SAN MATEO' Or (County.COUNTY)='SANTA CLARA' Or (County.COUNTY)='SANTA CRUZ' Or (County.COUNTY)='SOLANO' Or (County.COUNTY)='SONOMA') AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY [002_DateInput].SystemCreateDate DESC";

    $Alit_BAY_North = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput].Address, [002_DateInput].City, [002_DateInput].State, [002_DateInput].Zip, [002_DateInput].Phone, [002_DateInput].[Job Group] AS [Job Group1], County.COUNTY AS County1, '---------' AS Stop, [002_DateInput].Date, [002_DateInput].SystemCreateDate, [003a27_05_Alit_BAY South].ID AS [ALIT BAY], [003a27_01_Alit_ALL_Kitchen Bathroom Decks].ID AS [All KBD], [002_DateInput].[Submitted Date], [002_DateInput].company, [002_DateInput].ID, Len(LeadsDb!conDayTimePhone) AS LengthPhone
FROM ((County INNER JOIN (002_DateInput INNER JOIN LeadsDb ON [002_DateInput].ID = LeadsDb.ID) ON County.ZIPCODE = [002_DateInput].Zip) LEFT JOIN [003a27_05_Alit_BAY South] ON LeadsDb.ID = [003a27_05_Alit_BAY South].ID) LEFT JOIN [003a27_01_Alit_ALL_Kitchen Bathroom Decks] ON LeadsDb.ID = [003a27_01_Alit_ALL_Kitchen Bathroom Decks].ID
WHERE (((County.COUNTY) Like 'Napa' Or (County.COUNTY)='Marin' Or (County.COUNTY)='Solano' Or (County.COUNTY)='Sonoma') AND (([003a27_05_Alit_BAY South].ID) Is Null) AND (([003a27_01_Alit_ALL_Kitchen Bathroom Decks].ID) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY [002_DateInput].SystemCreateDate DESC";

    $Alit_OR = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput_Alit_ALL JOB].Address, [002_DateInput_Alit_ALL JOB].City, [002_DateInput_Alit_ALL JOB].State, [002_DateInput_Alit_ALL JOB].Zip, [002_DateInput_Alit_ALL JOB].Phone, [002_DateInput_Alit_ALL JOB].[Job Group], '---------' AS Stop, LeadsDb.SystemCreateDate, [Shai Alit Cities Not].[Shai Alit Cities Not], County.COUNTY AS County, Len(LeadsDb!conDayTimePhone) AS LengthPhone, County.COUNTY
FROM [Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN (LeadsDb INNER JOIN [002_DateInput_Alit_ALL JOB] ON LeadsDb.ID = [002_DateInput_Alit_ALL JOB].ID) ON County.ZIPCODE = [002_DateInput_Alit_ALL JOB].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput_Alit_ALL JOB].City
WHERE ((([002_DateInput_Alit_ALL JOB].State)='OR') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Bath%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%deck%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Window%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%door%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10)) OR ((([002_DateInput_Alit_ALL JOB].State)='WA') AND (([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Bath%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%deck%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%Window%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%door%' And ([002_DateInput_Alit_ALL JOB].[Job Group]) Not Like '%renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((County.COUNTY)='Clark') AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY LeadsDb.SystemCreateDate DESC";

    $Alit_Austin = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput].Address, [002_DateInput].City, [002_DateInput].State, [002_DateInput].Zip, [002_DateInput].Phone, [002_DateInput].[Job Group] AS [Job Group1], '---------' AS Stop, [002_DateInput].SystemCreateDate, [Shai Alit 1 Austin Zip Mile Counter].Austin_Miles, [Shai Alit 1 Houston Zip Mile Counter].Houston_Miles, County.COUNTY AS County, [002_DateInput].Date, [002_DateInput].[Submitted Date], [002_DateInput].company, [002_DateInput].ID, Len(LeadsDb!conDayTimePhone) AS LengthPhone, [Shai Alit Cities Not].[Shai Alit Cities Not]
FROM [Shai Alit Cities Not] RIGHT JOIN ([Shai Alit 1 Houston Zip Mile Counter] RIGHT JOIN ([Shai Alit 1 Austin Zip Mile Counter] RIGHT JOIN (County INNER JOIN (002_DateInput INNER JOIN LeadsDb ON [002_DateInput].ID = LeadsDb.ID) ON County.ZIPCODE = [002_DateInput].Zip) ON [Shai Alit 1 Austin Zip Mile Counter].AustinZip = [002_DateInput].Zip) ON [Shai Alit 1 Houston Zip Mile Counter].HoustonZip = [002_DateInput].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput].City
WHERE ((([002_DateInput].Address) Not Like '12 main st') AND (([002_DateInput].State)='TX') AND (([002_DateInput].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput].[Job Group]) Not Like '%Bath%' And ([002_DateInput].[Job Group]) Not Like '%deck%' And ([002_DateInput].[Job Group]) Not Like '%Window%' And ([002_DateInput].[Job Group]) Not Like '%door%' And ([002_DateInput].[Job Group]) Not Like '%renovate%') AND (([Shai Alit 1 Austin Zip Mile Counter].Austin_Miles)<80) AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY [002_DateInput].SystemCreateDate DESC";

    $Alit_Houston = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput].Address, [002_DateInput].City, [002_DateInput].State, [002_DateInput].Zip, [002_DateInput].Phone, [002_DateInput].[Job Group] AS [Job Group1], '---------' AS Stop, [002_DateInput].SystemCreateDate, [Shai Alit 1 Austin Zip Mile Counter].Austin_Miles, [Shai Alit 1 Houston Zip Mile Counter].Houston_Miles, County.COUNTY AS County, [002_DateInput].Date, [002_DateInput].[Submitted Date], [002_DateInput].company, [002_DateInput].ID, Len(LeadsDb!conDayTimePhone) AS LengthPhone, [Shai Alit Cities Not].[Shai Alit Cities Not]
FROM [Shai Alit Cities Not] RIGHT JOIN ([Shai Alit 1 Houston Zip Mile Counter] RIGHT JOIN ([Shai Alit 1 Austin Zip Mile Counter] RIGHT JOIN (County INNER JOIN (002_DateInput INNER JOIN LeadsDb ON [002_DateInput].ID = LeadsDb.ID) ON County.ZIPCODE = [002_DateInput].Zip) ON [Shai Alit 1 Austin Zip Mile Counter].AustinZip = [002_DateInput].Zip) ON [Shai Alit 1 Houston Zip Mile Counter].HoustonZip = [002_DateInput].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput].City
WHERE ((([002_DateInput].State)='TX') AND (([002_DateInput].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput].[Job Group]) Not Like '%Bath%' And ([002_DateInput].[Job Group]) Not Like '%deck%' And ([002_DateInput].[Job Group]) Not Like '%Window%' And ([002_DateInput].[Job Group]) Not Like '%door%' And ([002_DateInput].[Job Group]) Not Like '%renovate%') AND (([Shai Alit 1 Houston Zip Mile Counter].Houston_Miles)<80) AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY [002_DateInput].SystemCreateDate DESC";

    $Alit_Dallas = "SELECT LeadsDb!conFirstName+' '+LeadsDb!conLastName AS Name, [002_DateInput].Address, [002_DateInput].City, [002_DateInput].State, [002_DateInput].Zip, [002_DateInput].Phone, [002_DateInput].[Job Group] AS [Job Group1], '---------' AS Stop, [002_DateInput].SystemCreateDate, County.COUNTY AS County, [002_DateInput].Date, [002_DateInput].[Submitted Date], [002_DateInput].company, [002_DateInput].ID, Len(LeadsDb!conDayTimePhone) AS LengthPhone, [Shai Alit Cities Not].[Shai Alit Cities Not]
FROM [Shai Alit Dallas Zip] INNER JOIN ([Shai Alit Cities Not] RIGHT JOIN (County INNER JOIN (002_DateInput INNER JOIN LeadsDb ON [002_DateInput].ID = LeadsDb.ID) ON County.ZIPCODE = [002_DateInput].Zip) ON [Shai Alit Cities Not].[Shai Alit Cities Not] = [002_DateInput].City) ON [Shai Alit Dallas Zip].[Dallas Zip] = [002_DateInput].Zip
WHERE ((([002_DateInput].State)='TX') AND (([002_DateInput].[Job Group]) Not Like '%Kitchen%' And ([002_DateInput].[Job Group]) Not Like '%Bath%' And ([002_DateInput].[Job Group]) Not Like '%deck%' And ([002_DateInput].[Job Group]) Not Like '%Window%' And ([002_DateInput].[Job Group]) Not Like '%door%' And ([002_DateInput].[Job Group]) Not Like '%renovate%') AND (([Shai Alit Cities Not].[Shai Alit Cities Not]) Is Null) AND ((Len([LeadsDb]![conDayTimePhone]))=10))
ORDER BY [002_DateInput].SystemCreateDate DESC";

    $sth = $db->prepare($Alit_Dallas);
    $sth->execute();

    while ($row = $sth->fetch(PDO::FETCH_ASSOC)) {
        print_r($row); exit;
    }
}
catch(PDOException $e) {
    echo $e->getMessage()."\n";
    exit;
}

// CLOSE CONNECTIONS
$accConn = null;
$myConn = null;

